### PR TITLE
🧪 Migrate test runners to Vitest

### PR DESCRIPTION
**Pull request by QuintonC**
## ℹ️ What is the context for these changes?

This is not related to any particular issue, but is part of our tech debt of unit tests. In my pursuit to add additional tests for the package, I've found that when attempting to test packages that are ESM only (such as wagmi), there are limitations imposed by the use of Jest.

To combat those limitations, reduce the overall configuration required to run tests, and to allow for quicker and more streamlined tests, I've added Vitest and removed Jest in this PR.

Additionally, I encourage you to review **each commit** individually as the overall number of files changed is quite large. Each commit was broken down into particular subsections of the changes that the PR encompasses. For example, the first commit adds Vitest and migrates connect-wallet. The subsequent PRs migrate individual packages, make changes to configs, remove jest, etc.

Key takeaways:
- Vitest supports **ESM**, TypeScript, and JSX out of the box and utilizes esbuild as the underlying bundler. Esbuild is the same bundler used by tsup and Vite. 
  - ESM support is one of the things we are missing in our test utilities at the moment and we are already having to work around ESM support in some of our tests in `main` (using a commit that is currently on main so this reference stays relevant in the future) [as seen here](https://github.com/Shopify/blockchain-components/commit/87bdf737039a431509016ee43787847ce0683410#diff-cd25ee320374c42e4af80541409f21595ae37ae0dac4ecf5a23cc9e8ea77fb39R12).
- It should also reduce the amount of time needed to run our test suites since it utilizes esbuild.
- Vitest should also increase the DX since Vitest utilizes HMR similar to how Vite operates meaning the [watch functionality is more seamless](https://vitest.dev/guide/features.html#watch-mode).
- Since this is running in conjunction with Turbo, the initial test run will likely take the same amount of time as the Jest runners did by themselves (my testing revealed the tests took 6.21s with Turbo and Vitest compared to 6.38s with Jest by itself) than Jest did by itself. Without utilizing Turbo to build the packages prior to running tests, you would experience the following:

```shell
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 3 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  packages/connect-wallet/src/middleware/onConnectMiddleware.test.ts [ packages/connect-wallet/src/middleware/onConnectMiddleware.test.ts ]
 FAIL  packages/connect-wallet/src/slices/walletSlice/attributeOrder.test.ts [ packages/connect-wallet/src/slices/walletSlice/attributeOrder.test.ts ]
 FAIL  packages/connect-wallet/src/slices/walletSlice/fetchEns.test.ts [ packages/connect-wallet/src/slices/walletSlice/fetchEns.test.ts ]
Error: Failed to resolve entry for package "@shopify/gate-context-client". The package may have incorrect main/module/exports specified in its package.json.
 ❯ packageEntryFailure node_modules/vite/dist/node/chunks/dep-ca21228b.js:22005:11
 ❯ resolvePackageEntry node_modules/vite/dist/node/chunks/dep-ca21228b.js:22002:5
 ❯ tryNodeResolve node_modules/vite/dist/node/chunks/dep-ca21228b.js:21737:20
 ❯ Context.resolveId node_modules/vite/dist/node/chunks/dep-ca21228b.js:21488:28
 ❯ Object.resolveId node_modules/vite/dist/node/chunks/dep-ca21228b.js:41612:46
 ❯ TransformContext.resolve node_modules/vite/dist/node/chunks/dep-ca21228b.js:41363:23
 ❯ normalizeUrl node_modules/vite/dist/node/chunks/dep-ca21228b.js:39698:34
 ❯ TransformContext.transform node_modules/vite/dist/node/chunks/dep-ca21228b.js:39840:47
 ❯ Object.transform node_modules/vite/dist/node/chunks/dep-ca21228b.js:41685:30

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ [1/3] ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 Test Files  3 failed | 5 passed (8)
      Tests  70 passed (70)
   Start at  15:40:22
   Duration  1.35s (transform 642ms, setup 993ms, collect 1.10s, tests 47ms)
```

The big win?

When running tests locally with Turbo after the first build is complete, your tests will be a lot faster ⚡ ⤵

```shell
 Tasks:    6 successful, 6 total
Cached:    6 cached, 6 total
  Time:    331ms >>> FULL TURBO

✨  Done in 0.47s.
```

## ✅ Checklist

- [ ] ~Tested on mobile~ N/A
- [ ] ~Tested on multiple browsers~ N/A
- [ ] ~Tested for accessibility~ N/A
- [x] Includes unit tests
- [x] Updated relevant documentation for the changes (if necessary)

### CODE REVIEW

**Comment by jamiely** [comment]
> when attempting to test packages that are ESM only (such as wagmi), there are limitations imposed by the use of Jest.

Can you add some info about this?

**Review by caropinzonsilva — APPROVED** [review]
I think moving towards Vite makes sense, the community in general is moving towards it. 

We don't have lots of tests, but I would keep an eye on performance of the tests as we continue adding more. I know that in general Vite is supposed to be faster than Jest, but I have read some cases in which this is not the case. 

Thanks for adding these changes!

**Comment by jamiely** [comment]
> The thumbs down are indicating requirements for Jest ESM support that we currently do not meet.

Just to clarify, the thumbs down next to this point:

```
Execute node with yarn node --experimental-vm-modules $(yarn bin jest) 👎
```

Is just a general thumbs down for using experimental support? It's not referring to something specific about the command or syntax of the command?

**Comment by QuintonC** [comment]
> > The thumbs down are indicating requirements for Jest ESM support that we currently do not meet.
> 
> 
> 
> Just to clarify, the thumbs down next to this point:
> 
> 
> 
> ```
> 
> Execute node with yarn node --experimental-vm-modules $(yarn bin jest) 👎
> 
> ```
> 
> 
> 
> Is just a general thumbs down for using experimental support? It's not referring to something specific about the command or syntax of the command?

Sorry, I should've been more clear. 

I was attempting to use emojis to signal where we would need changes in order to utilize an experimental feature. The emojis weren't a symbol of disinterest in making changes, but rather a symbol to showcase where we would need to make changes in order to begin using this experimental feature.

I edited the original comment with an emoji legend to hopefully provide more clarity for other folks reviewing in the future.

**Pull request merged**
