### PR TITLE
[Tailwind] Updates examples to include stylesheets

### PR DESCRIPTION
**Pull request by QuintonC**
## ℹ️ What is the context for these changes?

Updates examples in the examples directory to include the exported styles from the packages.

## 🎩 How can this be tophatted?

1. Pull this branch
2. Navigate to an example
3. Ensure that you do not have node_modules or yarn.lock in the example directory
4. `yarn install`
5. `yarn dev` or `yarn start` (for CRA)

### CODE REVIEW

**Review by jamiely — APPROVED** [review]
Seems to be working fine. I followed tophatting instructions, but I needed to `yarn install` in the root first.

**Comment by caropinzonsilva** [comment]
It is not working for me 🤔 
I tried with `nextjs` example and got this error:
15-39-ohqt3-rsktn

**Comment by caropinzonsilva** [comment]
Confirmed that it is also happening in the root after running `yarn install`:
15-42-w3lsv-drdfs

**Comment by caropinzonsilva** [comment]
It is also happening in `main` so it must be something unrelated to this PR.

**Review by caropinzonsilva — APPROVED** [review]
The changes look good, but I could not 🎩 due to an unrelated error in my machine

**Comment by jamiely** [comment]
@caropinzonsilva I suspect it is b/c of the node version. I recall that things didn't work right with node 19

**Pull request merged**
